chore: get back old version of e2e test workflow

diff --git a/.github/workflows/karate-testing.yml b/.github/workflows/karate-testing.yml
--- a/.github/workflows/karate-testing.yml
+++ b/.github/workflows/karate-testing.yml
@@ -1,11 +1,13 @@
-name: Run karate tests in isolation using local env
+name: Run karate tests (docker compose and local env)
 
 on:
   push:
-    branches: [ feature/* ]
+    branches:
+      - master
+  pull_request:
 
 jobs:
-  e2e-test:
+  e2e-test-with-local-env:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout local-env
@@ -33,8 +35,6 @@ jobs:
         
       - name: Download Karate JAR
         run: |
-          cd ..
-          cd inner-circle-compensations-api/
           curl -L https://github.com/karatelabs/karate/releases/download/v1.5.1/karate-1.5.1.jar -o karate.jar
 
       - name: Run Karate Tests
@@ -45,5 +45,35 @@ jobs:
           API_ROOT_URL: "http://localhost:40100"
           AUTH_LOGIN: "ceo@tourmalinecore.com"
           AUTH_PASSWORD: "cEoPa$$wo1d"
-
+  
+  e2e-test-without-local-env:
+    # Image to run project and tests
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+    - name: Run service via docker-compose and run Karate-tests
+    # Hide credentials and token from logs, get the number of failed and passed tests
+    # Find text with 'failed' and 'passed' in logs from karate-testing container
+      run: |
+        LOGS=$(docker compose --profile MockForPullRequest up --abort-on-container-exit)
+        FILTERED_LOGS=$(echo "$LOGS" | sed -E 's/"login":"[^"]*"/"login":"****"/g' \
+                                 | sed -E 's/"password":"[^"]*"/"password":"****"/g' \
+                                 | sed -E 's/"accessToken":[^,}]*"[^"]*"/"accessToken":"****"/g' \
+                                 | sed -E 's/"Authorization":"[^"]*"/"Authorization":"****"/g' \
+                                 | sed -E 's/"X-DEBUG-TOKEN":[^,}]*"[^"]*"/"X-DEBUG-TOKEN":"****"/g' \
+                                 | sed -E 's/accessToken":\{[^}]*\}/accessToken":{"value":"****"}/g' \
+                                 | sed -E 's/X-DEBUG-TOKEN: [^ ]*/X-DEBUG-TOKEN: ****/g') 
+        echo "$FILTERED_LOGS"
+        FAILED=$(echo "$FILTERED_LOGS" | grep -oP 'failed: *\K\d+')
+        PASSED=$(echo "$FILTERED_LOGS" | grep -oP 'passed: *\K\d+')
+        echo "Failed tests: $FAILED"
+        echo "Passed tests: $PASSED"
+        if [ "$FAILED" -gt 0 ]; then
+          echo "Failed tests found! Failing the pipeline..."
+          exit 1
+        fi
+        if [ "$PASSED" -eq 0 ]; then
+          echo "No tests passed! Failing the pipeline..."
+          exit 1
+        fi        
           
