ci(karate): change rule to run pipeline on pull request on feature branches, count passed tests and fail if it's number is 0

diff --git a/.github/workflows/karate-testing.yml b/.github/workflows/karate-testing.yml
--- a/.github/workflows/karate-testing.yml
+++ b/.github/workflows/karate-testing.yml
@@ -1,11 +1,9 @@
 name: Karate Local Testing
 
 on:
-    push:
-      branches:
-        - 'feature/*' 
-        
-    pull_request:
+  pull_request:
+    branches:
+      - 'feature/*'
 
 env:
   GITHUB_REGISTRY: ghcr.io
@@ -26,8 +24,14 @@ jobs:
       # We waiting for `passed: <number of passed tests>` in logs
       run: |
         FAILED=$(docker-compose -f docker-compose-test.yaml logs karate-tests | grep -oP 'failed: *\K\d+')
+        PASSED=$(docker-compose -f docker-compose-test.yaml logs karate-tests | grep -oP 'passed: *\K\d+')
         echo "Failed tests: $FAILED"
+        echo "Passed tests: $PASSED"
         if [ $FAILED -gt 0 ]; then
           echo "Failed tests found! Failing the pipeline..."
+          exit 1
+        fi
+        if [ $PASSED -eq 0 ]; then
+          echo "No tests passed! Failing the pipeline..."
           exit 1
         fi
