ci: try to hide sensitive data from logs in github actions

diff --git a/.github/workflows/karate-testing.yml b/.github/workflows/karate-testing.yml
--- a/.github/workflows/karate-testing.yml
+++ b/.github/workflows/karate-testing.yml
@@ -12,34 +12,6 @@ on:
 env:
   GITHUB_REGISTRY: ghcr.io
 
-jobs:
-  test:
-    # Image to run project and tests
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - name: Run service via docker-compose
-      # Run project via docker-compose. 
-      # Use --abort-on-container-exit flag to stop all containers when tests were passed or failed to free up resources.
-      run: |
-        docker-compose -f docker-compose-test.yaml up --abort-on-container-exit > docker-compose-logs.txt
-    - name: Extract test results from karate container logs
-      # Extract test results from container logs
-      # We waiting for `passed: <number of passed tests>` in logs
-      run: |
-        # Read logs from file
-        FAILED=$(docker-compose -f docker-compose-test.yaml logs karate-tests | grep -oP 'failed: *\K\d+')
-        PASSED=$(docker-compose -f docker-compose-test.yaml logs karate-tests | grep -oP 'passed: *\K\d+')
-        echo "Failed tests: $FAILED"
-        echo "Passed tests: $PASSED"
-        if [ $FAILED -gt 0 ]; then
-          echo "Failed tests found! Failing the pipeline..."
-          exit 1
-        fi
-        if [ $PASSED -eq 0 ]; then
-          echo "No tests passed! Failing the pipeline..."
-          exit 1
-        fi
 # jobs:
 #   test:
 #     # Image to run project and tests
@@ -50,11 +22,12 @@ jobs:
 #       # Run project via docker-compose. 
 #       # Use --abort-on-container-exit flag to stop all containers when tests were passed or failed to free up resources.
 #       run: |
-#         docker-compose -f docker-compose-test.yaml up --abort-on-container-exit
+#         docker-compose -f docker-compose-test.yaml up --abort-on-container-exit > docker-compose-logs.txt
 #     - name: Extract test results from karate container logs
 #       # Extract test results from container logs
 #       # We waiting for `passed: <number of passed tests>` in logs
 #       run: |
+#         # Read logs from file
 #         FAILED=$(docker-compose -f docker-compose-test.yaml logs karate-tests | grep -oP 'failed: *\K\d+')
 #         PASSED=$(docker-compose -f docker-compose-test.yaml logs karate-tests | grep -oP 'passed: *\K\d+')
 #         echo "Failed tests: $FAILED"
@@ -67,3 +40,30 @@ jobs:
 #           echo "No tests passed! Failing the pipeline..."
 #           exit 1
 #         fi
+jobs:
+  test:
+    # Image to run project and tests
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+    - name: Run service via docker-compose
+      # Run project via docker-compose. 
+      # Use --abort-on-container-exit flag to stop all containers when tests were passed or failed to free up resources.
+      run: |
+        docker-compose -f docker-compose-test.yaml up --abort-on-container-exit
+    - name: Extract test results from karate container logs
+      # Extract test results from container logs
+      # We waiting for `passed: <number of passed tests>` in logs
+      run: |
+        FAILED=$(docker-compose -f docker-compose-test.yaml logs karate-tests | grep -oP 'failed: *\K\d+')
+        PASSED=$(docker-compose -f docker-compose-test.yaml logs karate-tests | grep -oP 'passed: *\K\d+')
+        echo "Failed tests: $FAILED"
+        echo "Passed tests: $PASSED"
+        if [ $FAILED -gt 0 ]; then
+          echo "Failed tests found! Failing the pipeline..."
+          exit 1
+        fi
+        if [ $PASSED -eq 0 ]; then
+          echo "No tests passed! Failing the pipeline..."
+          exit 1
+        fi
