test: try to run e2e on production

diff --git a/.github/workflows/karate-testing.yml b/.github/workflows/karate-testing.yml
--- a/.github/workflows/karate-testing.yml
+++ b/.github/workflows/karate-testing.yml
@@ -39,3 +39,30 @@ jobs:
           echo "No tests passed! Failing the pipeline..."
           exit 1
         fi
+
+  production-test:
+    # Image to run project and tests
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+    - name: Set up Docker Compose environment variables
+      run: |
+        echo AUTH_LOGIN=${{ secrets.AUTH_LOGIN }} >> .env
+        echo AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }} >> .env
+    - name: Run service via docker-compose and run Karate-tests
+      run: |
+        LOGS=$(docker-compose --profile production-e2e-tests up --abort-on-container-exit)
+        FILTERED_LOGS=$(echo "$LOGS" | sed -E 's/"login":"[^"]*"/"login":"****"/g' | sed -E 's/"password":"[^"]*"/"password":"****"/g')
+        echo "$FILTERED_LOGS"
+        FAILED=$(echo "$FILTERED_LOGS" | grep -oP 'failed: *\K\d+')
+        PASSED=$(echo "$FILTERED_LOGS" | grep -oP 'passed: *\K\d+')
+        echo "Failed tests: $FAILED"
+        echo "Passed tests: $PASSED"
+        if [ "$FAILED" -gt 0 ]; then
+          echo "Failed tests found! Failing the pipeline..."
+          exit 1
+        fi
+        if [ "$PASSED" -eq 0 ]; then
+          echo "No tests passed! Failing the pipeline..."
+          exit 1
+        fi
