chore: update deploy workflow

diff --git a/.github/workflows/prod-docker-publish.yml b/.github/workflows/prod-docker-publish.yml
--- a/.github/workflows/prod-docker-publish.yml
+++ b/.github/workflows/prod-docker-publish.yml
@@ -1,13 +1,9 @@
-name: Deploy to Prod
+name: Deploy to Prod and e2e test to prod
 
 on:
   push:
     branches:
       - master
-  pull_request:
-
-env:
-  GITHUB_REGISTRY: ghcr.io
 
 jobs:
   # this is needed to wait for the new docker image to be build and published to the registry
@@ -47,41 +43,43 @@ jobs:
             --state-values-set extraSecretEnvVars.InnerCircleServiceUrls__EmployeesServiceUrl=${{ secrets.EMPLOYEES_SERVICE_URL }}
           helmfile-auto-init: "false"
 
-  production-test:
-    # Image to run project and tests
+  e2e-test-prod:
+    runs-on: ubuntu-22.04
     needs: [deploy-to-prod]
-    name: Run e2e on production
-    if: github.event_name == 'push'
-    runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    # Get secrets to sign in
-    - name: Set up Docker Compose environment variables
-      run: |
-        echo AUTH_LOGIN=${{ secrets.AUTH_LOGIN }} >> .env
-        echo AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }} >> .env
-    - name: Run service via docker-compose and run Karate-tests
-    # Hide credentials and token from logs, get the number of failed and passed tests
-      run: |
-        LOGS=$(docker compose --profile production-e2e-tests up --abort-on-container-exit)
-        FILTERED_LOGS=$(echo "$LOGS" | sed -E 's/"login":"[^"]*"/"login":"****"/g' \
-                                 | sed -E 's/"password":"[^"]*"/"password":"****"/g' \
-                                 | sed -E 's/"accessToken":[^,}]*"[^"]*"/"accessToken":"****"/g' \
-                                 | sed -E 's/"Authorization":"[^"]*"/"Authorization":"****"/g' \
-                                 | sed -E 's/"X-DEBUG-TOKEN":[^,}]*"[^"]*"/"X-DEBUG-TOKEN":"****"/g' \
-                                 | sed -E 's/accessToken":\{[^}]*\}/accessToken":{"value":"****"}/g' \
-                                 | sed -E 's/X-DEBUG-TOKEN: [^ ]*/X-DEBUG-TOKEN: ****/g' \
-                                 | sed -E 's/Authorization: [^ ]*/Authorization: ****/g')
-        echo "$FILTERED_LOGS"
-        FAILED=$(echo "$FILTERED_LOGS" | grep -oP 'failed: *\K\d+')
-        PASSED=$(echo "$FILTERED_LOGS" | grep -oP 'passed: *\K\d+')
-        echo "Failed tests: $FAILED"
-        echo "Passed tests: $PASSED"
-        if [ "$FAILED" -gt 0 ]; then
-          echo "Failed tests found! Failing the pipeline..."
-          exit 1
-        fi
-        if [ "$PASSED" -eq 0 ]; then
-          echo "No tests passed! Failing the pipeline..."
-          exit 1
-        fi
+      - name: Check out the repo
+        uses: actions/checkout@v4
+
+      # Get secrets to sign in
+      - name: Set up Docker Compose environment variables
+        run: |
+          echo AUTH_LOGIN=${{ secrets.AUTH_LOGIN }} >> .env
+          echo AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }} >> .env
+      
+      - name: Run service via docker-compose and run Karate-tests
+        run: |
+          # Get logs
+          LOGS=$(docker compose --profile production-e2e-tests up --abort-on-container-exit)
+          # Filter logs and mask sensitive information
+          FILTERED_LOGS=$(echo "$LOGS" | sed -E 's/"login":"[^"]*"/"login":"****"/g' \
+                                  | sed -E 's/"password":"[^"]*"/"password":"****"/g' \
+                                  | sed -E 's/"accessToken":[^,}]*"[^"]*"/"accessToken":"****"/g' \
+                                  | sed -E 's/"Authorization":"[^"]*"/"Authorization":"****"/g' \
+                                  | sed -E 's/"X-DEBUG-TOKEN":[^,}]*"[^"]*"/"X-DEBUG-TOKEN":"****"/g' \
+                                  | sed -E 's/accessToken":\{[^}]*\}/accessToken":{"value":"****"}/g' \
+                                  | sed -E 's/X-DEBUG-TOKEN: [^ ]*/X-DEBUG-TOKEN: ****/g' \
+                                  | sed -E 's/Authorization: [^ ]*/Authorization: ****/g')
+          echo "$FILTERED_LOGS"
+          # Count failed and passed tests
+          FAILED=$(echo "$FILTERED_LOGS" | grep -oP 'failed: *\K\d+')
+          PASSED=$(echo "$FILTERED_LOGS" | grep -oP 'passed: *\K\d+')
+          echo "Failed tests: $FAILED"
+          echo "Passed tests: $PASSED"
+          if [ "$FAILED" -gt 0 ]; then
+            echo "Failed tests found! Failing the pipeline..."
+            exit 1
+          fi
+          if [ "$PASSED" -eq 0 ]; then
+            echo "No tests passed! Failing the pipeline..."
+            exit 1
+          fi
